Repository pallets-eco/cachelib, pull requests merged in 2021-06, with the labels that each got.

#17 Support windows path
  src/cachelib/file.py
Labels: enhancement, windows

#15 fix: don`t cout at files overwrite
  CHANGES.rst
  src/cachelib/file.py
  tests/test_file_system_cache.py
Labels: bug

#41 Remove old _compat type groups and iterator
  src/cachelib/_compat.py
  src/cachelib/base.py
  src/cachelib/file.py
  src/cachelib/memcached.py
  src/cachelib/redis.py
Labels: codebase update

#44 Remove hookwrapper=True from pytest_sessionfinish
  tests/conftest.py
Labels: tests

#43 Release 0.2.0
  CHANGES.rst
  src/cachelib/__init__.py
Labels: release
