Repository pallets-eco/cachelib, pull requests merged in 2021-08, with the labels that each got.

#59 Change: pip link
  README.rst
Labels: docs

#54 Released 0.3.0
  CHANGES.rst
  src/cachelib/__init__.py
Labels: release

#48 Add type hinting
  .github/workflows/tests.yaml
  CHANGES.rst
  MANIFEST.in
  requirements.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/typing.in
  requirements/typing.txt
  setup.cfg
  src/cachelib/base.py
  src/cachelib/file.py
  src/cachelib/memcached.py
  src/cachelib/py.typed
  src/cachelib/redis.py
  src/cachelib/simple.py
  src/cachelib/uwsgi.py
  tox.ini
Labels: typing
