Repository pallets-eco/cachelib, pull requests merged in 2024-02, with the labels that each got.

#345 Drop py37, add py310 and py311, drop flaky macos tests and fix broken docs
  .github/workflows/lock.yaml
  .github/workflows/tests.yaml
  .gitignore
  .readthedocs.yaml
  setup.cfg
  src/cachelib/file.py
  src/cachelib/simple.py
  tox.ini
Labels: codebase update

#347 Release 0.11.0
  CHANGES.rst
  src/cachelib/__init__.py
Labels: release

#348 Add callable key support for RedisCache
  CHANGES.rst
  src/cachelib/redis.py
  tests/test_redis_cache.py
Labels: enhancement

#214 Mongodb backend
  .github/workflows/tests.yaml
  CHANGES.rst
  docs/index.rst
  docs/mongodb.rst
  requirements/dev.txt
  requirements/docs.txt
  requirements/tests.in
  requirements/tests.txt
  requirements/typing.txt
  src/cachelib/__init__.py
  src/cachelib/base.py
  src/cachelib/mongodb.py
  tests/test_mongodb_cache.py
Labels: new feature, ongoing review

#349 release 0.12.0
  CHANGES.rst
  src/cachelib/__init__.py
Labels: release
